# clean the env
rm(list=ls(all=T))

# set the working directory 
setwd("C:/Users/amith/Desktop/project/R code")

# load the libraries
x = c("ggplot2", "corrgram", "DMwR", "caret", "randomForest", "unbalanced", "C50", "dummies", "e1071", "Information",
     "MASS", "rpart", "gbm", "ROSE", 'sampling', 'DataCombine', 'inTrees')

# install packages
lapply(x , require, character.only =TRUE)
rm(x)

## read the data
marketing_train=read.csv("marketing_tr.csv", header = T, na.strings = c(" ", "", "NA"))

str(marketing_train)

## exploratory data analysis(Univariate Analysis and Variable Consolidation)

marketing_train$schooling[marketing_train$schooling %in% "illiterate"] = "unknown"
marketing_train$schooling[marketing_train$schooling %in% c("basic.4y","basic.6y","basic.9y","high.school","professional.course")] = "high.school"
marketing_train$default[marketing_train$default %in% "yes"] = "unknown"
marketing_train$default = as.factor(as.character(marketing_train$default))
marketing_train$marital[marketing_train$marital %in% "unknown"] = "married"
marketing_train$marital = as.factor(as.character(marketing_train$marital))
marketing_train$month[marketing_train$month %in% c("sep","oct","mar","dec")] = "dec"
marketing_train$month[marketing_train$month %in% c("aug","jul","jun","may","nov")] = "jun"
marketing_train$month = as.factor(as.character(marketing_train$month))
marketing_train$loan[marketing_train$loan %in% "unknown"] = "no"
marketing_train$loan = as.factor(as.character(marketing_train$loan))
marketing_train$schooling = as.factor(as.character(marketing_train$schooling))
marketing_train$profession[marketing_train$profession %in% c("management","unknown","unemployed","admin.")] = "admin."
marketing_train$profession[marketing_train$profession %in% c("blue-collar","housemaid","services","self-employed","entrepreneur","technician")] = "blue-collar"
marketing_train$profession = as.factor(as.character(marketing_train$profession))



##### missing value analysis ####

# count of missing values in a particular value(total sum)
sum(is.na(marketing_train$custAge))

# create a dataframe with missing percentage
missing_val = data.frame(apply(marketing_train , 2, function(x) sum(is.na(x))))

# convert row names into columns
missing_val$columns=row.names(missing_val)
row.names(missing_val)=NULL

# rename the variable name
names(missing_val)[1]="missing_percentage"

# calculate the percentage
missing_val$missing_percentage = (missing_val$missing_percentage /nrow(marketing_train))*100

# arrange in descending order
missing_val = missing_val[order(-missing_val$missing_percentage),]

# re-arrange the columns
missing_val = missing_val[,c(2,1)]

# write in csv file
write.csv(missing_val, "missing_percentage" , row.names=F)

## use the impute methods(mean , median & KNN) to apply the missing values in the dataset##
# the method which gives the nearest value will be selected and imputation will be done#
## in order to do that select the  existing value value in a column from any variable##

# selecting the existing value in the dataset
marketing_train[70,1] #29(value of [70,1])
marketing_train[70,1] = NA

# actual value = 29
# mean = 40.01
# median = 38
# knn = 36.18 (best method as it is nearest to the actual value 29)
# after imputing the each method make sure to do the exploratory analysis once again

# Mean Method
marketing_train$custAge[is.na(marketing_train$custAge)] = mean(marketing_train$custAge, na.rm = T)

# median method
marketing_train$custAge[is.na(marketing_tain$custAge)] = median(marketing_train$custAge , na.rm =T)

# kNN Imputation(value of k always to be an odd number)
marketing_train = knnImputation(marketing_train, k = 3)

# check the missing values in the dataset
sum(is.na(marketing_train))

# write the missing values in a csv file
write.csv(marketing_train, 'marketing_train_missing.csv', row.names = F)

## Data Manupulation : convert string categories into factor numeric
for(i in 1:ncol(marketing_train)){
  
  if(class(marketing_train[,i]) == 'factor'){
    
    marketing_train[,i] = factor(marketing_train[,i], labels=(1:length(levels(factor(marketing_train[,i])))))
    
  }
}

############################################Outlier Analysis#############################################
# ## BoxPlots - Distribution and Outlier Check
numeric_index = sapply(marketing_train,is.numeric) #selecting only numeric

numeric_data = marketing_train[,numeric_index]

# store the numeric data in the columns
cnames = colnames(numeric_data)
 
# using the ggplot to all the variables to plot the graph by assigning the values from (gn1 to gn11) for the independent vars
for (i in 1:length(cnames))
 {
   assign(paste0("gn",i), ggplot(aes_string(y = (cnames[i]), x = "responded"), data = subset(marketing_train))+ 
            stat_boxplot(geom = "errorbar", width = 0.5) +
            geom_boxplot(outlier.colour="red", fill = "grey" ,outlier.shape=18,
                         outlier.size=1, notch=FALSE) +
            theme(legend.position="bottom")+
            labs(y=cnames[i],x="responded")+
            ggtitle(paste("Box plot of responded for",cnames[i])))
 }

 
### Plotting plots together
gridExtra::grid.arrange(gn1,gn5,gn2,ncol=3)
gridExtra::grid.arrange(gn6,gn7,ncol=2)
gridExtra::grid.arrange(gn8,gn9,ncol=2)

## after the outlier analysis is done make sure to remove it for further analysis 

# remove the outliers using boxplot method
df = marketing_train

# detect the outliers and remove them using boxplot.stats (built in) function
val =marketing_train$previous[marketing_train$previous %in% boxplot.stats(marketing_train$previous) $out]

# remove the observation which contains the outliers
marketing_train = marketing_train[which(!marketing_train$previous %in% val),]

marketing_train =df

# loop to remove the outliers from all the observations
for(i in cnames)
{
print(i)
val = marketing_train[,i][marketing_train[,i]] %in% boxplot.stats(marketing_train[,i])$out]
marketing_train[,i][marketing_train[,i] %in% val] = NA
}

# impute knn
marketing_train = knnImputation(marketing_train , k=3)

## error occured to due to shortage of observations after taking out all the missing values






